### ISSUE TITLE
[Duvida] - Relacionamento das entidades Loc e Cob

### ISSUE THREAD

**Issue by devandremachado** [bacen/pix-api#496]
Até o momento, entendi que o intuito da **Location** é permitir a sua reutilização em diferentes cobranças  (não simultâneamente) no caso de QR Code dinâmico.  

Dito isso, entendo o fluxo de uma cobrança imediata da seguinte forma:

`POST/loc` => **Location** criada e sem nenhuma **Cobrança** vinculada até o momento.

`POST/cob` => **Cobrança** criada, e no body da request pode ser referenciado uma **Location** pré-existente através do `loc.id`.
- Neste ponto, se informado o `loc.id` na criação da **Cobrança**, a entidade **Location** agora faz referência à uma **Cobrança** pelo seu **txId**.

- O Usuário Pagador, realiza a leitura do QrCode atráves do seu PSP Recebedor que tem acesso as informações da **Cobrança** a partir da URL da **Location** através do endpoint público **CobPayload** `GET/{pixUrlAccessToken}`.

- Após o pagamento, o PSP Pagador é notificado e recebe `EndToEndId` referente a um `Pix`. 

Para reaproveitar o mesmo QrCode o sistema de automação poderá desvincular a **Cobrança** de uma **Location** através do endpoint `DELETE/loc/{id}/txid`.

- Neste ponto, a entidade **Location**  NÃO faz referência à nenhuma **Cobrança**, removendo a referência do `txId`, e com isso, poderá ser criado outra **Cobrança** `POST/cob` informando o mesmo `loc.id` e seguirá novamente com o fluxo utilizando o mesmo QrCode. (fazendo sentido no "mundo físico" um QrCode impresso em papel na frente de um caixa, por exemplo)

Primeiramente, eu gostaria confirmar se o meu entendimento do fluxo acima está correto. Pressupondo que sim, tenho 2 dúvidas:

1. Após desvincular a **Cobrança** de uma **Location**, quando o usuário realizar a consulta de cobrança que já foi paga `GET/cob/{txId}` deverá ser exibido a **Location** que originou essa **Cobrança** antes de ser desvinculada? Sendo que essa **Location** já poderá estar sendo utilizada em outra **Cobrança**?

---

2. O PSP Pagador pode NÃO oferecer os endpoints de [PayloadLocation](https://bacen.github.io/pix-api/index.html#/PayloadLocation)? 
O que eu quero dizer é, sem oferecer ao usuário da api-pix gerencie o PayLoadLocation o consumidor da API não irá conseguir criar/desvincular uma **Location** e reutiliza-lo em outras **Cobranças** e, por consequência, sempre será gerado um QrCode diferente para cada **Cobrança** (e-commerce). Neste cenário, o usuário da api-pix só terá acesso a URL do **Location** para gerar o QrCode.

**Comment by lucas-marc** [comment]
Hi everyone,

I’m researching a payment flow similar to the “printed dynamic QR Code” described in section 6.2.4 of the Pix Initiation Standards Manual.

From the documentation, it seems that in order to reuse a single printed dynamic QR Code across multiple payments (similar to the model used by large PSPs in Brazil), the following is required:

1. creating a fixed payload location via POST /loc,

2. creating a cob associated with that loc,

3. and after the payment, disassociating the cob using DELETE /loc/{id}/txid, leaving the location “clean” for the next transaction.

My questions:

- Is this understanding correct? Are loc and its endpoints required for implementing a reusable, printed dynamic QR Code?

- Are there PSPs already offering these endpoints (POST /loc, DELETE /loc/{id}/txid, etc.) to integrators?

I'm evaluating some providers, but many seem to expose only /cob. Without loc, it seems impossible to support the official “printed dynamic QR flow”. Is there any other option or alternative in case those endpoints aren't provided?

Thank you!

**Comment by lucas-marc** [comment]
@devandremachado I understand you had a similar enquiry, not sure if you were able to resolve it. Sorry I'm using english, my Portuguese is not very good. Can switch to Spanish if better, or try with automatic translation tools!
